POST  http://localhost:3000/bill-Summary HTTP/1.1
content-type: application/json

{
    "minutes":20000, 
    "dataUsage":5,
    "smsCount":200,
    "plan":"basic"
}

######

POST  http://localhost:3000/total-bill HTTP/1.1
content-type: application/json

{
    "minutes":20000, 
    "dataUsage":5,
    "smsCount":200,
    "plan":"basic"
}


######

POST  http://localhost:3000/predict-bill HTTP/1.1
content-type: application/json

{
    "minutesUsed":20000, 
    "dataUsedGB":5,
    "smsCount":200,
    "plan":"premium"
}

######

POST  http://localhost:3000/Outages HTTP/1.1
content-type: application/json

{
    "region": "New York",
    "phoneNumber": 1234567890
}